;;; replique-main-js-test.el --- Tests for the module a page loads  -*- lexical-binding: t; -*-

;;; Commentary:

;; What an application's own page includes in order to reach a process's
;; ClojureScript.  The file itself is the process's to write and is tested
;; where it is written; what is here is the editor's half - reading back
;; what a module already names, asking for one, and saying what came of it.
;;
;; And the other end of the same namespace: a module names the program its
;; page loads, the page finds that program on disk only where something
;; compiled it, and what compiles it is a repl started on it.  So the menu a
;; ClojureScript repl offers is read out of these files, which is where
;; replique 1 read it too - those tests are at the bottom.
;;
;; Most of that needs no process: what goes out is a message and what comes
;; back is a frame, and a plist is a plist however it arrived.  The one at
;; the end uses a process, because what is being checked there is that the
;; op this sends is an op a process answers.

;;; Code:

(require 'ert)
(require 'cl-lib)
(require 'seq)
(require 'replique-test)
(require 'replique-main-js)
(require 'replique-repl)

(defun replique-main-js-test--module (main &optional marker)
  "Return the text of a main module whose page loads MAIN, a string or nil.

MARKER stands in for the first line, for the files that are not ours.
The rest is written the way the process writes it: four constants, each
on a line of its own, under a header nobody reads."
  (concat (or marker replique-main-js--marker)
          " - autogenerated, and rewritten every time a repl starts\n"
          "//\n"
          "// Include this from your own page:\n"
          "//   <script type=\"module\" src=\"this file\"></script>\n"
          "//\n"
          "const host = \"127.0.0.1\";\n"
          "const port = \"59280\";\n"
          (format "const mainNs = %s;\n" (if main (format "\"%s\"" main) "null"))
          (format "const mainPath = %s;\n"
                  (if main (format "\"%s.js\"" (replace-regexp-in-string
                                                "[.]" "/" main))
                    "null"))
          "\nconst base = \"http://\" + host + \":\" + port + \"/\";\n"))

(defmacro replique-main-js-test--with-module (name text &rest body)
  "Run BODY with NAME bound to a file holding TEXT."
  (declare (indent 2))
  `(let ((,name (make-temp-file "replique-main-js-test" nil ".js" ,text)))
     (unwind-protect (progn ,@body)
       (delete-file ,name))))

;;; Reading one back

(ert-deftest replique-main-js-test-a-module-names-the-program-its-page-loads ()
  "Which is what is offered when it is written again: a module written a
second time is usually one being moved rather than one whose program
changed, and nothing but the file itself remembers which program that is."
  (replique-main-js-test--with-module file (replique-main-js-test--module "my.app")
    (should (equal "my.app" (replique-main-js--names file)))))

(ert-deftest replique-main-js-test-a-page-that-loads-nothing-names-nothing ()
  "A repl in a page of yours with no program in it is a thing to want, and
the module writes null where the name would be.  Nil and not \"null\",
which would be offered back as a namespace to compile."
  (replique-main-js-test--with-module file (replique-main-js-test--module nil)
    (should-not (replique-main-js--names file))))

(ert-deftest replique-main-js-test-only-a-module-of-ours-is-read ()
  "The first line is the whole of how one is recognised.  Replique 1's file
is the one that matters here - the two markers were chosen not to be
prefixes of one another, so that neither replique rewrites the other's
file - but any .js at all can be chosen by mistake, and what is read out
of one is a namespace this would then offer to write into it."
  (replique-main-js-test--with-module
      file (replique-main-js-test--module
            "my.app" "//main-js-file autogenerated by replique")
    (should-not (replique-main-js--names file)))
  (replique-main-js-test--with-module
      file (replique-main-js-test--module "my.app" "// some bundler")
    (should-not (replique-main-js--names file))))

(ert-deftest replique-main-js-test-only-the-head-of-a-file-is-read ()
  "A project is full of .js files that are megabytes of somebody else's
bundle, and choosing one by mistake must not be an editor reading all of
it.  The constants are in the first few hundred characters, so a file
claiming to be ours and answering past the bound answers nothing."
  (replique-main-js-test--with-module
      file (concat replique-main-js--marker "\n"
                   (make-string (* 2 replique-main-js--head) ?x) "\n"
                   "const mainNs = \"my.app\";\n")
    (should-not (replique-main-js--names file))))

(ert-deftest replique-main-js-test-a-file-that-is-not-there-names-nothing ()
  "Which is the first write: the name of a file nobody has written yet is
a perfectly good answer to where one should go."
  (should-not (replique-main-js--names "/nowhere/at/all/main.js"))
  (should-not (replique-main-js--names nil)))

;;; Asking for one

(defun replique-main-js-test--asked (file main)
  "Return the message `replique-main-js' sends for FILE and MAIN."
  (let ((sent nil))
    (cl-letf (((symbol-function 'replique-process-request)
               (lambda (_process msg _callback) (setq sent msg))))
      (replique-main-js file main (replique-process--make :directory "/p/")))
    sent))

(ert-deftest replique-main-js-test-what-is-asked-for-is-the-file-and-the-program ()
  "The process writes it and this says where, so the where is the whole of
what goes out - beside the program the page is to load."
  (should (equal '(:op :main-js :file "/p/public/main.js" :main "my.app")
                 (replique-main-js-test--asked "/p/public/main.js" "my.app"))))

(ert-deftest replique-main-js-test-a-page-that-loads-nothing-carries-no-main ()
  "Left out rather than sent as nil: absent is how the protocol writes a
module that names no program, and a key whose value is null would be a
client saying the same thing a second way."
  (should (equal '(:op :main-js :file "/p/public/main.js")
                 (replique-main-js-test--asked "/p/public/main.js" nil))))

(ert-deftest replique-main-js-test-a-relative-file-goes-out-as-it-was-written ()
  "Relative to the directory the process was started in, which is the
process's answer to give and not this one's: expanding it here against
whatever buffer was current would send a path about the editor."
  (should (equal '(:op :main-js :file "public/main.js")
                 (replique-main-js-test--asked "public/main.js" nil))))

;;; What came of it

(defun replique-main-js-test--said (frame)
  "Return what `replique-main-js' says when the process answers FRAME."
  (let ((said nil))
    (cl-letf (((symbol-function 'replique-process-request)
               (lambda (_process _msg callback) (funcall callback frame)))
              ((symbol-function 'message)
               (lambda (format &rest args) (setq said (apply #'format format args)))))
      (replique-main-js "/p/public/main.js" "my.app"
                        (replique-process--make :directory "/p/")))
    said))

(ert-deftest replique-main-js-test-what-was-written-is-said ()
  "Three facts and all three are wanted: where it landed, which program its
page will load, and which process it will load it from - the last being
the one thing that was not known before it was asked for.  The file is
named the way somebody working in the project names it."
  (let ((said (replique-main-js-test--said
               '(:tag "reply" :file "/p/public/main.js"
                 :url "http://127.0.0.1:59280/" :main "my.app"))))
    (should (string-match-p "public/main.js" said))
    (should-not (string-match-p "/p/public" said))
    (should (string-match-p "my.app" said))
    (should (string-match-p "59280" said))))

(ert-deftest replique-main-js-test-a-module-that-loads-nothing-says-so ()
  "Rather than saying it loads nothing by not mentioning a program, which
reads as an answer that lost half of itself."
  (let ((said (replique-main-js-test--said
               '(:tag "reply" :file "/p/public/main.js"
                 :url "http://127.0.0.1:59280/"))))
    (should (string-match-p "loads nothing" said))
    (should (string-match-p "59280" said))))

(ert-deftest replique-main-js-test-a-file-outside-the-project-keeps-its-path ()
  "A relative name climbing out of the project says less than the path it
is a longer way of writing, and an application's assets are as likely to
be somewhere else as not."
  (let ((said (replique-main-js-test--said
               '(:tag "reply" :file "/elsewhere/public/main.js"
                 :url "http://127.0.0.1:59280/" :main "my.app"))))
    (should (string-match-p "/elsewhere/public/main.js" said))))

(ert-deftest replique-main-js-test-a-refusal-is-shown-and-claims-nothing ()
  "A process with no ClojureScript compiler refuses this with a sentence
about its classpath.  What must not happen is what would happen if the
answer were read as a reply: an error frame carries no file, and naming
one would be an editor saying a file was written that is not there."
  (let ((said (replique-main-js-test--said
               '(:tag "error" :error "no-cljs"
                 :message "This process cannot run a ClojureScript repl"))))
    (should (string-match-p "cannot run a ClojureScript repl" said))
    (should-not (string-match-p "main.js" said))
    (should-not (string-match-p "loads" said))))

;;; The prompts

(ert-deftest replique-main-js-test-what-the-file-already-names-is-offered ()
  "As text rather than as a default, so that it can be cleared: with a
default, return is the only thing the prompt can be answered with and a
module that names a program could never be made to name none."
  (replique-main-js-test--with-module file (replique-main-js-test--module "my.app")
    (let ((initial 'unasked)
          (offered nil))
      (cl-letf (((symbol-function 'replique-name-process)
                 (lambda () (replique-process--make :directory "/p/")))
                ((symbol-function 'replique-namespaces)
                 (lambda (_process &optional _keys) '("my.app" "my.other")))
                ((symbol-function 'read-file-name)
                 (lambda (&rest _) file))
                ((symbol-function 'completing-read)
                 (lambda (_prompt table &optional _p _r init &rest _)
                   (setq initial init offered table)
                   "")))
        (let ((read (replique-main-js--read)))
          (should (equal "my.app" initial))
          (should (equal '("my.app" "my.other") offered))
          ;; and an empty answer is a page that loads nothing, which is
          ;; what clearing the text is for
          (should (equal (list file nil) (list (nth 0 read) (nth 1 read))))
          (should (replique-process-p (nth 2 read))))))))

(ert-deftest replique-main-js-test-the-namespaces-asked-for-are-the-browsers ()
  "There is one main module and it is the browser's: a node runtime has no
page to include one.  So the names offered are the names that side of the
process has, whichever repl happens to be open."
  (replique-main-js-test--with-module file (replique-main-js-test--module nil)
    (let ((keys 'unasked))
      (cl-letf (((symbol-function 'replique-name-process)
                 (lambda () (replique-process--make :directory "/p/")))
                ((symbol-function 'replique-namespaces)
                 (lambda (_process &optional asked) (setq keys asked) nil))
                ((symbol-function 'read-file-name) (lambda (&rest _) file))
                ((symbol-function 'completing-read) (lambda (&rest _) "my.app")))
        (replique-main-js--read))
      (should (equal '(:dialect :cljs :target :browser) keys)))))

;;; And a process

(ert-deftest replique-main-js-test-the-process-is-asked-and-answers ()
  "Whichever process it is.  One with the ClojureScript compiler on its
classpath writes the file - and what it writes is a module this reads
back, which is the whole round trip - while one without it refuses by
name.  Either way the op is an op a process answers, which is what
nothing short of a process can say."
  (replique-test-with-project dir
    (let ((file (expand-file-name "public/main.js" dir))
          (said nil))
      (cl-letf (((symbol-function 'message)
                 (lambda (format &rest args) (push (apply #'format format args) said))))
        (replique-main-js file "my.app" (replique-test-process))
        (should (replique-test-wait-for
                 (lambda ()
                   (seq-find (lambda (line)
                               (string-match-p "loads my.app\\|ClojureScript" line))
                             said))
                 120)))
      (let ((line (seq-find (lambda (l) (string-match-p "loads my.app\\|ClojureScript" l))
                            said)))
        (if (file-exists-p file)
            (progn
              (should (string-match-p "loads my.app from http" line))
              (should (equal "my.app" (replique-main-js--names file))))
          (should (string-match-p "ClojureScript" line)))))))

;;; Starting a repl on what a module names

(defun replique-main-js-test--menu (frame)
  "Return the namespaces read out of FRAME, the answer to `:main-modules'."
  (cl-letf (((symbol-function 'replique-process-request-sync)
             (lambda (_process _msg &optional _timeout) frame)))
    (replique-repl--main-namespaces (replique-process--make :directory "/p/"))))

(ert-deftest replique-main-js-test-the-menu-is-what-the-modules-name ()
  "Which programs this project can be started on, which is the whole of what
`mainNs' is in the file for: the browser imports `mainPath' and never reads
the name.  Sorted and without repeats - two pages loading one program is an
ordinary thing, and the order a walk came back in says nothing."
  (should (equal '("my.admin" "my.app")
                 (replique-main-js-test--menu
                  '(:tag "reply"
                    :modules ((:file "/p/b/main.js" :main "my.app")
                              (:file "/p/a/main.js" :main "my.admin")
                              (:file "/p/c/main.js" :main "my.app")))))))

(ert-deftest replique-main-js-test-a-module-that-loads-nothing-is-not-on-the-menu ()
  "The process answers it all the same, because what it found is a fact about
the files.  What is being offered here is a namespace to compile, and a
module that names none names none."
  (should-not (replique-main-js-test--menu
               '(:tag "reply" :modules ((:file "/p/a/main.js")))))
  (should (equal '("my.app")
                 (replique-main-js-test--menu
                  '(:tag "reply" :modules ((:file "/p/a/main.js")
                                           (:file "/p/b/main.js" :main "my.app")))))))

(ert-deftest replique-main-js-test-a-menu-that-cannot-be-built-is-no-menu ()
  "And not an error: this is the convenience half of opening a repl, and a
command that refused to open one because a walk could not be done would be
refusing over the part nobody asked for.  A process too old to know the op
refuses it, and one that has stopped answering answers nothing at all."
  (should-not (replique-main-js-test--menu
               '(:tag "error" :error "unknown-op" :message "no such op")))
  (should-not (replique-main-js-test--menu nil))
  (should-not (replique-main-js-test--menu '(:tag "reply" :modules nil))))

(defun replique-main-js-test--hello (main)
  "Return the handshake a browser repl started on MAIN is opened with."
  (let ((hello 'unasked)
        (replique-current-repl nil)
        (process (replique-process--make :id "p" :host "127.0.0.1" :port 1)))
    (cl-letf (((symbol-function 'replique-conn-open)
               (lambda (_host _port _kind &rest keys)
                 (setq hello (plist-get keys :hello))
                 nil))
              ((symbol-function 'pop-to-buffer) #'ignore))
      (let ((repl (replique-repl process :cljs :browser main)))
        (kill-buffer (replique-repl--buffer repl))))
    hello))

(ert-deftest replique-main-js-test-the-repl-is-started-on-the-program-chosen ()
  "Which is what closes the loop: the page imports what its module names, and
that import finds a module on disk only where something compiled it.  The
handshake is where a repl says which namespace to compile before its first
prompt, so this is the key that makes an opened page load a program."
  (should (equal '(:dialect :cljs :target :browser :main "my.app")
                 (replique-main-js-test--hello "my.app"))))

(ert-deftest replique-main-js-test-a-repl-standing-in-no-program-carries-no-main ()
  "Left out rather than sent as nil, as the dialect and the target are: an
absent key is how the protocol writes a repl that was not started on
anything."
  (should (equal '(:dialect :cljs :target :browser)
                 (replique-main-js-test--hello nil))))

(defun replique-main-js-test--asked-for (answers)
  "Return what `replique-repl--read' reads, ANSWERS answering its prompts.

ANSWERS maps a word of a prompt to what is typed at it.  A prompt that is
not in it is a prompt this did not expect to be shown."
  (let ((current-prefix-arg '(4)))
    (cl-letf (((symbol-function 'replique-process-current)
               (lambda () (replique-process--make :directory "/p/")))
              ((symbol-function 'replique-repl--main-namespaces)
               (lambda (_process) '("my.admin" "my.app")))
              ((symbol-function 'completing-read)
               (lambda (prompt &rest _)
                 (or (cdr (seq-find (lambda (each)
                                      (string-match-p (car each) prompt))
                                    answers))
                     (error "Asked for %s" prompt)))))
      (replique-repl--read))))

(ert-deftest replique-main-js-test-a-clojure-repl-is-not-asked-which-program ()
  "A namespace to compile before the first prompt is a ClojureScript
question, as the target is.  Nothing about a Clojure repl is answered by
it, and a prompt shown there would be one to press return through."
  (let ((read (replique-main-js-test--asked-for '(("Dialect" . "clj")))))
    (should (equal :clj (nth 1 read)))
    (should-not (nth 2 read))
    (should-not (nth 3 read))))

(ert-deftest replique-main-js-test-a-clojurescript-repl-is-asked-which-program ()
  "And what it is offered is what the main modules name."
  (let ((read (replique-main-js-test--asked-for '(("Dialect" . "cljs")
                                                  ("Target" . "browser")
                                                  ("Main namespace" . "my.app")))))
    (should (replique-process-p (nth 0 read)))
    (should (equal :cljs (nth 1 read)))
    (should (equal :browser (nth 2 read)))
    (should (equal "my.app" (nth 3 read)))))

(ert-deftest replique-main-js-test-an-empty-answer-is-a-repl-on-nothing ()
  "Which is why the menu is offered as text rather than as a default: with a
default, return is the only answer the prompt has and a repl standing in no
particular program could not be asked for."
  (let ((initial 'unasked)
        (offered nil))
    (cl-letf (((symbol-function 'replique-repl--main-namespaces)
               (lambda (_process) '("my.admin" "my.app")))
              ((symbol-function 'completing-read)
               (lambda (_prompt table &optional _p _r init &rest _)
                 (setq offered table initial init)
                 "  ")))
      (should-not (replique-repl--read-main
                   (replique-process--make :directory "/p/")))
      (should (equal '("my.admin" "my.app") offered))
      (should (equal "my.admin" initial)))))

(provide 'replique-main-js-test)

;;; replique-main-js-test.el ends here
